---
layout: page
---

## Publications

## 2023

| Title                                                                                                                                                   | Authors              | Journal                            |
|-----------------------|-------------------------|-----------------------|
| [Development of a peripheral blood transcriptomic gene signature to predict bronchopulmonary dysplasia](https://pubmed.ncbi.nlm.nih.gov/36472344/)      | Moreira, A *et al*   | Am J Physiol Lung Cell Mol Physiol |
| [Prediction of extubation failure among low birthweight neonates using machine learning](https://pubmed.ncbi.nlm.nih.gov/36611107/)                     | Natarajan, A *et al* | J Perinatol                        |
| [Machine learning: remember the fundamentals](https://pubmed.ncbi.nlm.nih.gov/36550355/)                                                                | Beam, K *et al*      | J Pediatr Res                      |
| [Improving child health through Big Data and data science](https://pubmed.ncbi.nlm.nih.gov/35974162/)                                                   | Vesoulis, Z *et al*  | Pediatr Res                        |
| [Emerging role of artificial intelligence, big data analysis and precision medicine in pediatrics](https://pubmed.ncbi.nlm.nih.gov/36807652/)           | Malhotra, A *et al*  | Pediatr Res                        |
| [From computer to bedside, involving neonatologists in artificial intelligence models for neonatal medicine](https://pubmed.ncbi.nlm.nih.gov/36526854/) | Vijlbrief, D *et al* | Pediatr Res                        |
| [Artificial intelligence in the diagnosis of necrotising enterocolitis in newborns](https://pubmed.ncbi.nlm.nih.gov/36195629/)                          | Sitek, A *et al*     | Pediatr Res                        |
| [Multiomics, artificial intelligence, and precision medicine in perinatology](https://pubmed.ncbi.nlm.nih.gov/35804156/)                                | Pammi, M *et al*     | Pediatr Res                        |

## 2022

| Title                                                                                                                                                                                                                      | Authors               | Journal                        |
|-----------------------|-------------------------|-----------------------|
| [Interpretable prediction of necrotizing enterocolitis from machine learning analysis of premature infant stool microbiota](https://pubmed.ncbi.nlm.nih.gov/35337258/)                                                     | Lin, Y *et al*        | BMC Bioinformatics             |
| [Use of an electronic medical record to optimize a neonatal sepsis score for mortality prediction](https://pubmed.ncbi.nlm.nih.gov/36450852/)                                                                              | Husain, A *et al*     | J Perinatol                    |
| [Artificial and human intelligence for early identification of neonatal sepsis](https://pubmed.ncbi.nlm.nih.gov/36127407/)                                                                                                 | Sullivan, B *et al*   | Pediatr Res                    |
| [Artificial intelligence in pediatrics: the future is now](https://pubmed.ncbi.nlm.nih.gov/35115711/)                                                                                                                      | Knake, L              | Pediatr Res                    |
| [Artificial intelligence for the diagnosis of retinopathy of prematurity: A systematic review of current algorithms](https://pubmed.ncbi.nlm.nih.gov/36577806/)                                                            | Ramanathan, A *et al* | Eye                            |
| [Pivotal challenges in artificial intelligence and machine learning applications for neonatal care](https://pubmed.ncbi.nlm.nih.gov/36266181/)                                                                             | Jeong, H *et al*      | Semin Fetal Neonatal Med       |
| [Machine learning for prediction of bronchopulmonary dysplasia-free survival among very preterm infants](https://pubmed.ncbi.nlm.nih.gov/36100848/)                                                                        | Leigh, R *et al*      | BMC Pediatr                    |
| [Development and Validation of a Deep Learning Method to Predict Cerebral Palsy From Spontaneous Movements in Infants at High Risk](https://pubmed.ncbi.nlm.nih.gov/35816301/)                                             | Groos, D *et al*      | JAMA Netw Open                 |
| [Development and Validation of a Deep Learning Model to Predict the Occurrence and Severity of Retinopathy of Prematurity](https://pubmed.ncbi.nlm.nih.gov/35708686/)                                                      | Wu, Q *et al*         | JAMA Netw Open                 |
| [Machine Learning Prediction Models for Neurodevelopmental Outcome After Preterm Birth: A Scoping Review and New Machine Learning Evaluation Framework](https://pubmed.ncbi.nlm.nih.gov/35670123/)                         | Boven, M *et al*      | Pediatrics                     |
| [Machine learning for understanding and predicting neurodevelopmental outcomes in premature infants: a systematic review](https://pubmed.ncbi.nlm.nih.gov/35641551/)                                                       | Baker, S *et al*      | Pediatr Res                    |
| [NeoAI 1.0: Machine learning-based paradigm for prediction of neonatal and infant risk of death](https://pubmed.ncbi.nlm.nih.gov/35635905/)                                                                                | Teji, J *et al*       | Comput Biol Med                |
| [Early severity prediction of BPD for premature infants from chest X-ray images using deep learning: A study at the 28th day of oxygen inhalation](https://pubmed.ncbi.nlm.nih.gov/35576685/)                              | Xing, W *et al*       | Comput Methods Programs Biomed |
| [Predicting clinical outcomes using artificial intelligence and machine learning in neonatal intensive care units: a systematic review](https://pubmed.ncbi.nlm.nih.gov/35562414/)                                         | McAdams, R *et al*    | J Perinatol                    |
| [Identifying clinical phenotypes in extremely low birth weight infants-an unsupervised machine learning approach](https://pubmed.ncbi.nlm.nih.gov/34734319/)                                                               | Matsushita, F *et al* | Eur J Pediatr                  |
| [Language function following preterm birth: prediction using machine learning](https://pubmed.ncbi.nlm.nih.gov/34635792/)                                                                                                  | Valavani, E *et al*   | Pediatr Res                    |
| [Machine Learning Used to Compare the Diagnostic Accuracy of Risk Factors, Clinical Signs and Biomarkers and to Develop a New Prediction Model for Neonatal Early-onset Sepsis](https://pubmed.ncbi.nlm.nih.gov/34508027/) | Stocker, M *et al*    | Pediatr Infect Dis J           |
